name: Manual Deployment

on:
  push:
    branches:
      - tet*
  workflow_dispatch:
    inputs:
        environment2:
          description: 'Environment to deploy into'
          type: environment
          default: 'stg'
          required: true

jobs:
  deploy:
    name: Deploy 2 
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'dev'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: Deploy
        run: |
          # Add deployment commands here
          echo "Deploying branch ${{ github.event.ref }} env:${ENVIRONMENT}"

