name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Deploy
        run: |
          # Add deployment commands here
          echo "Deploying branch ${{ github.event.inputs.branch }}"
