name: Manual Deployment

on:
  push:
    branches:
      - tete
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: Deploy
        run: |
          # Add deployment commands here
          echo "Deploying branch ${{ github.event.ref }}"

