name: Manual Deployment

on:
  push:
    refs:
      - refs/heads/tete*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test code
        run: |
          # Add build and test commands here
          echo "Building and testing code"
