name: Manual2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          # Add deployment commands here
          echo "Deploying to ${{ github.event.inputs.environment }}"
